sudo: required

services:
- docker

language: java
jdk: openjdk8

before_install:
- mkdir -p ~/Documents/sftp
- cp .maven.settings.xml "$HOME"/.m2/settings.xml
- mvn fmt:check

install: mvn install -DskipTests -DskipITs -Ddocker.skip -Ddockerfile.skip -Dmaven.javadoc.skip=true -Dhttp.wait.skip -B -V

script: mvn verify cobertura:cobertura-integration-test

after_success:
- if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ] ; then
  docker login -u "${DOCKER_GCP_USERNAME}" -p "${DOCKER_GCP_PASSWORD}" "${DOCKER_GCP_REGISTRY}";
  docker push "eu.gcr.io/census-rm-ci/rm/census-rm-actionexportersvc";
  fi
- if [ "$TRAVIS_BRANCH" == "RMC-111-Manifest-File" ] ; then
  docker login -u "${DOCKER_GCP_USERNAME}" -p "${DOCKER_GCP_PASSWORD}" "${DOCKER_GCP_REGISTRY}";
  docker tag "census-rm-actionexporter-service" "census-rm-actionexporter-service:ade_test";
  docker push "census-rm-actionexporter-service:ade_test";
  fi
- bash <(curl -s https://codecov.io/bash)

cache:
  directories:
  - $HOME/.m2

branches:
  only:
    - master
