//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference
// Implementation, v2.2.11
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2019.06.26 at 12:02:53 PM BST
//

@javax.xml.bind.annotation.XmlSchema(
    namespace = "http://ons.gov.uk/ctp/response/action/message/instruction")
package uk.gov.ons.ctp.response.action.export.actioninstuction;
